### ISSUE TITLE
The content from the "Lockwise" onboarding page is not centered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla-lockwise/lockwise-addon#267]
**[Affected Versions]:**
- Lockwise 2.2.1-alpha
- Firefox 67 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Perquisites]:**
- Have the latest Firefox 67 version installed.
- Have the Lockwise 2.2.1 - alpha extension installed.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockwise" toolbar button.
3. Click the "Open Lockwise" button.
4. Observe the "Lockwise" onboarding page.

**[Expected results]:**
- All the elements from the onboarding page are correctly displayed and rendered.

**[Actual results]:**
- The page content is not centered.

**[Notes]:**
- This issue is also reproducible on the management page if a saved login is focused.
- Attached a screen recording with the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/58172273-c4cea780-7ca0-11e9-86e7-8bb2a50b5d47.gif)

**Comment by WesleyBranton** [comment]
This is because the inline rule for `.app__aside___2DsyN` has a `width: 320px;` rule on line 48 of inline stylesheet 25 that is overriding the `.app__app-main___19DOF` selector's `grid-template-columns: 1fr 3fr;` rule on the inline stylesheet 25 line 28. Either removing the width rule or setting the grid-template-columns to `0fr 3fr` fixes the issue.

I can patch this if no one else is currently working on it.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the lockwise-signed.xpi (2.2.4) add-on on Windows 10 x64, Arch Linux and Mac 10.14.4 using Firefox Beta 68.0b11.
