### ISSUE TITLE
Master Password

### ISSUE THREAD

**Issue by nasirkhan** [mozilla-lockwise/lockwise-addon#324]
I installed the addon on Ubuntu 18.04 and i had to uninstall immediately. I use firefox default password manager with the `Master Password` feature enabled. But here i could not find any such feature, all my saved passwords are like displaying in plain text. 

Is there any plan to make any feature like `Master Password` in future?

**Comment by NobleUplift** [comment]
Completely agree!!! There's one principle reason why I refuse to use LastPass and it's because of this right here. If you're using LastPass and you leave your computer unlocked, all someone has to do is open your LastPass Vault, click that useless eye symbol, close the tab, and you'd be none the wiser.

Firefox Lockwise uninstalled. I'm not using an addon that reduces the security of Firefox to that of LastPass or Google Chrome. Firefox is the best browser of all time, let's not weaken it by turning it into its competitors.

**Comment by maverick74** [comment]
So, if i go it strait, what is being requested here is that when opening Lockwise (or when clicking the "view password" icon on the lockwise tab), a master password is asked for before user can view or copy  a user's login password, is that right?

If so, count me as interested as well!

**Comment by eggsgent** [comment]
> 
> 
> So, if i got it strait, what is being requested here is that when opening Lockwise page (or when clicking the "view password" icon on the lockwise tab), a master password is asked for before user can view or copy a user's login password, is that right?
> 
> If so, count me as interested as well!

That's how it works in Firefox Windows build 70.0b6

**Comment by mnoorenberghe** [comment]
Master password support was implemented in Firefox 70. You should not use the extension with Fx70+ as it is built-in and the extension will no longer be supported.

**Comment by matijakovacevic** [comment]
Just want to know how secure is this?

As I've read that Firefox master password login, from before, was pretty 'crackable'.
Is this up to par with Lastpass, Bitwarden and the rest, concerning security?

I'm looking into switching from Lastpass, ergo, my questions
