### ISSUE TITLE
Can't reveal/copy passwords in about:logins

### ISSUE THREAD

**Issue by gcp** [mozilla-lockwise/lockwise-addon#340]
Current Nightly, issue on macOS and Windows

Menu -> Logins And Passwords -> enter something in search, e.g. Bugzilla.

See stored login.

Press any "Copy" button: no effect, no visual feedback of press.
Click "eyes": no effect.

**Comment by SoftVision-CosminMuntean** [comment]
@gcp Do you have the Lockwsie add-on installed or are you using the Lockwise Password Manager built in the browser?

I'm asking this because there is an issue in the Lockwise feature from Nightly. The issue is because of the Mobile Promo displayed at the bottom of the page. If you dismiss the Mobile Promo everything works as expected. The issue is tracked in Bugzilla: [bug 1574869](https://bugzilla.mozilla.org/show_bug.cgi?id=1574869).

**Comment by gcp** [comment]
I'm pretty sure that is the bug yes. I didn't file in Bugzilla because that said to file Lockwise bugs here :-/
