### ISSUE TITLE
Feature request: Edit-able website addresses

### ISSUE THREAD

**Issue by rs410ga** [mozilla-lockwise/lockwise-addon#366]
For example. I have a username and password for my business website: evilcorp.com

I have to login to several different subdomains: email.evilcorp.com, expenses.evilcorp.com, training.evilcorp.com, benefits.evilcorp.com.

Each time I log in to a new subdomain, lockwise creates a new username/password entry. If there were more granular control over the address, I could edit the address to *.evilcorp.com which would include all subdomains. However, if there were a subdomain that I did in fact need to use a different username and password then I could also specify that subdomain.evilcorp.com.

Great addon, looking forward to switching to this password manager full time!

**Comment by markc** [comment]
The fact that Lockwise stores passwords for subdomains within a single parent domain namespace makes this otherwise great product useless for us. If I go to webmail.evilcorp.com I DO NOT want to see suggestions for all my other something.evilcorp.com subdomains. I can't for the life of me think of a good reason to amalgamate all subdomain password with the parent domain. I'm also getting complaints from our customers using our webmail system with Firefox and I have no solution other to start looking for yet another password manager!

**Comment by cadeyrn** [comment]
@markc: This has nothing to do with Lockwise. You can disable the lookup for other subdomains by setting signon.includeOtherSubdomainsInLookup to false in about:config.

**Comment by TimVevida** [comment]
I just ran into the same issue @markc mentioned and found it very annoying that I had to edit this via the about:config page (though thanks for the tip). Is it a possibility that this setting is presented on the main Lockwise page (about:logins), maybe even as a domain setting?

**Comment by mnoorenberghe** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1324394
