### ISSUE TITLE
Annoying pop-up

### ISSUE THREAD

**Issue by ThibaultSouchet** [mozilla-lockwise/lockwise-addon#382]
Hi there, 

Since i use Lockwise i always have a **** popup appearing randomly asking me to enter my master password when using Firefox.

Is anyone there encountering the same problem?

Thx,

**Comment by mnoorenberghe** [comment]
If you are still using the Lockwise extension, please remove it and restart Firefox to use the functionality which is built-into Firefox. You may need to reset the pref `signon.management.overrideURI` in about:config too depending on which version of the extension you are using.

If it's not from the extension, you may be seeing the master password prompt from Sync trying to log in. That is expected behaviour.

**Comment by ThibaultSouchet** [comment]
Sadly it is the second option.... thank you!
